version: "2.4"

services:
  queueing-back-1:
    image: ayeah77/integrated-queueing
    container_name: queueing01
    environment:
      - SERVER_NAME=queueing01
    ports:
      - "8081:8081"
    depends_on:
      kafka-1:
        condition: service_healthy # service_healthy는 고정된 이름 값
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis-sentinel01:
        condition: service_healthy
      redis-sentinel02:
        condition: service_healthy
      redis-sentinel03:
        condition: service_healthy
    networks:
      - integrated-net

  queueing-back-2:
    image: ayeah77/integrated-queueing
    container_name: queueing02
    environment:
      - SERVER_NAME=queueing02
    ports:
      - "8082:8081"
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis-sentinel01:
        condition: service_healthy
      redis-sentinel02:
        condition: service_healthy
      redis-sentinel03:
        condition: service_healthy
    networks:
      - integrated-net

  queueing-back-3:
    image: ayeah77/integrated-queueing
    container_name: queueing03
    environment:
      - SERVER_NAME=queueing03
    ports:
      - "8083:8081"
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      redis-sentinel01:
        condition: service_healthy
      redis-sentinel02:
        condition: service_healthy
      redis-sentinel03:
        condition: service_healthy
    networks:
      - integrated-net

  nginx:
    image: nginx:latest
    container_name: integrated-nginx

    # 호스트에서 8079 포트로 접속하면, 컨테이너 내부의 90 포트로 연결
    ports:
      - "8079:90"
    # nginx.conf 파일을 nginx 컨테이너에 마운트
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - queueing-back-1
      - queueing-back-2
      - queueing-back-3
#      - integrated-reserve-1
#      - integrated-reserve-2
#      - integrated-reserve-3
    networks:
      - integrated-net

  # Kafka Broker를 3대 실행시켜 Cluster 구조로 구성
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-1
    healthcheck: # 5초마다 health check를 수행하여 Kafka 브로커가 정상적으로 기동되어 요청을 처리할 수 있는 상태인지 확인
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 5s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A==' # 동일한 Cluster로 설정
    ports:
      - "9092:9092"
    networks:
      - integrated-net

  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-2
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 5s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
    ports:
      - "9093:9092"
    networks:
      - integrated-net

  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-3
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 5s
      timeout: 10s
      retries: 15
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
    ports:
      - "9094:9092"
    networks:
      - integrated-net

  kafka-cli:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-cli
    entrypoint: /bin/sh
    tty: true
    networks:
      - integrated-net

  redis-master:
    image: "bitnami/redis:latest"
    hostname: redis-master
    container_name: queue-redis-master
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes # 비밀번호 없이
    ports:
      - "6379:6379"
    networks:
      - integrated-net

  redis-slave01:
    image: "bitnami/redis:latest"
    hostname: redis-slave01
    container_name: queue-redis-slave01
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
    ports:
      - "6479:6379"
    depends_on:
      - redis-master
    networks:
      - integrated-net

  redis-slave02:
    image: "bitnami/redis:latest"
    hostname: redis-slave02
    container_name: queue-redis-slave02
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
    ports:
      - "6579:6379"
    depends_on:
      - redis-master
    networks:
      - integrated-net

  redis-sentinel01:
    image: 'bitnami/redis-sentinel:latest'
    hostname: redis-sentinel01
    container_name: queue-redis-sentinel01
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "26379", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000 # redis 노드에서 설정값 동안 응답이 없으면 down으로 판단
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000 # failover 타임아웃, 설정값동안 failover가 완료되지 않는다면 다른 Sentinel이 재시도 (10초, 기본은 180초)
      - REDIS_SENTINEL_PARALLEL_SYNCS=1 # Failover 이후, Slave들이 새 Master와 동기화할 때 동시에 몇 개까지 sync 할지
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=toMaster
      - REDIS_SENTINEL_QUORUM=2 # 장애 판단을 확정하기 위해 2개 ( 과반수 )의 sentinel 동의가 필요
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave01:
          condition: service_healthy
      redis-slave02:
          condition: service_healthy

    ports:
      - '26379:26379'
    networks:
      - integrated-net

  redis-sentinel02:
    image: 'bitnami/redis-sentinel:latest'
    hostname: redis-sentinel02
    container_name: queue-redis-sentinel02
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "26379", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=toMaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave01:
        condition: service_healthy
      redis-slave02:
        condition: service_healthy
    ports:
      - '26380:26379'
    networks:
      - integrated-net

  redis-sentinel03:
    image: 'bitnami/redis-sentinel:latest'
    hostname: redis-sentinel03
    container_name: queue-redis-sentinel03
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "26379", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=10000
      - REDIS_SENTINEL_PARALLEL_SYNCS=1
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=toMaster
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      redis-master:
        condition: service_healthy
      redis-slave01:
        condition: service_healthy
      redis-slave02:
        condition: service_healthy
    ports:
      - '26381:26379'
    networks:
      - integrated-net

networks:
  integrated-net: