worker_processes auto; # 워커 프로세스의 수를 CPU 코어 개수만큼 할당

events {
    worker_connections 1024; # 각 워커 프로세스 당 요청을 1024개 처리하도록 설정
}

http {
    upstream queueing-cluster {
        server queueing-back-1:8081;
        server queueing-back-2:8081;
        server queueing-back-3:8081;
    }

    upstream reserve-cluster {
        server integrated-reserve-1:8080;
        server integrated-reserve-2:8080;
        server integrated-reserve-3:8080;
    }

    server {
        listen 90;

        # 90포트로 기본 요청은 대기열로 라우팅
        location / {
            proxy_set_header Origin $http_origin;

            proxy_set_header Access-Control-Request-Method $http_access_control_request_method;
            proxy_set_header Access-Control-Request-Headers $http_access_control_request_headers;
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://queueing-cluster;
        }

        # 90포트로 /api/ 요청은 예약으로 라우팅
        location /api/ {
            proxy_set_header Origin $http_origin;

            proxy_set_header Access-Control-Request-Method $http_access_control_request_method;
            proxy_set_header Access-Control-Request-Headers $http_access_control_request_headers;
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://reserve-cluster;
        }
    }
}