events {}

http {
    upstream backend_cluster {
        server queueing-back-1:8081;
        server queueing-back-2:8081;
        server queueing-back-3:8081;
    }

    server {
        listen 90;

        # 90포트로 요청이 오면 Nginx는 그 요청을 backend_cluster라는 이름의 서버 그룹으로 전달(proxy)
        location / {
            proxy_pass http://backend_cluster;
        }
    }
}