spring.application.name=Integrated
server.port=8081

queue.validation.key=park
move.to.allow.interval=5000

spring.r2dbc.url=r2dbc:mysql://host.docker.internal:3306/integrated_queueing?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
spring.r2dbc.username=root
spring.r2dbc.password=tiffndla0423
spring.r2dbc.initialize-schema=always

spring.redis.host=redis-master
spring.redis.port=6379

spring.redis.sentinel.master=toMaster
spring.redis.sentinel.nodes=redis-sentinel01:26379,redis-sentinel02:26379,redis-sentinel03:26379

spring.kafka.producer.bootstrap-servers=kafka:9092
queue.event.topic.name=queueing-system

spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=integrated-consumer_${SERVER_NAME}
spring.kafka.consumer.auto-offset-reset=earliest

# host.docker.internal